/* This file was generated by PyBindGen 0.0.0.0 */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stddef.h>


#if PY_VERSION_HEX >= 0x03000000
#if PY_VERSION_HEX >= 0x03050000
typedef PyAsyncMethods* cmpfunc;
#else
typedef void* cmpfunc;
#endif
#define PyCObject_FromVoidPtr(a, b) PyCapsule_New(a, NULL, b)
#define PyCObject_AsVoidPtr(a) PyCapsule_GetPointer(a, NULL)
#define PyString_FromString(a) PyBytes_FromString(a)
#define Py_TPFLAGS_CHECKTYPES 0 /* this flag doesn't exist in python 3 */
#endif


#if     __GNUC__ > 2
# define PYBINDGEN_UNUSED(param) param __attribute__((__unused__))
#elif     __GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ > 4)
# define PYBINDGEN_UNUSED(param) __attribute__((__unused__)) param
#else
# define PYBINDGEN_UNUSED(param) param
#endif  /* !__GNUC__ */

#ifndef _PyBindGenWrapperFlags_defined_
#define _PyBindGenWrapperFlags_defined_
typedef enum _PyBindGenWrapperFlags {
   PYBINDGEN_WRAPPER_FLAG_NONE = 0,
   PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED = (1<<0),
} PyBindGenWrapperFlags;
#endif


#include "../src/mSDIF.hpp"
/* --- forward declarations --- */


typedef struct {
    PyObject_HEAD
    MSDIFMatrix *obj;
    PyBindGenWrapperFlags flags:8;
} PyMSDIFMatrix;


extern PyTypeObject PyMSDIFMatrix_Type;


typedef struct {
    PyObject_HEAD
    MSDIFFrame *obj;
    PyBindGenWrapperFlags flags:8;
} PyMSDIFFrame;


extern PyTypeObject PyMSDIFFrame_Type;

static PyMethodDef minisdifpy_functions[] = {
    {NULL, NULL, 0, NULL}
};
/* --- classes --- */



static int
_wrap_PyMSDIFMatrix__tp_init(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    const char *signature;
    Py_ssize_t signature_len;
    unsigned int rows;
    unsigned int columns;
    unsigned int type;
    const char *keywords[] = {"signature", "rows", "columns", "type", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "s#III", (char **) keywords, &signature, &signature_len, &rows, &columns, &type)) {
        return -1;
    }
    self->obj = new MSDIFMatrix(std::string(signature, signature_len), rows, columns, type);
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}


PyObject *
_wrap_PyMSDIFMatrix_rows(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    int retval;

    retval = self->obj->rows();
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_columns(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    int retval;

    retval = self->obj->columns();
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_newSize(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    unsigned int rows;
    unsigned int columns;
    const char *keywords[] = {"rows", "columns", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "II", (char **) keywords, &rows, &columns)) {
        return NULL;
    }
    self->obj->newSize(rows, columns);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_resize(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    unsigned int rows;
    unsigned int columns;
    const char *keywords[] = {"rows", "columns", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "II", (char **) keywords, &rows, &columns)) {
        return NULL;
    }
    self->obj->resize(rows, columns);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_resizeRows(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    unsigned int rows;
    const char *keywords[] = {"rows", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "I", (char **) keywords, &rows)) {
        return NULL;
    }
    self->obj->resizeRows(rows);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_addRow(PyMSDIFMatrix *self)
{
    PyObject *py_retval;

    self->obj->addRow();
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_addColumn(PyMSDIFMatrix *self)
{
    PyObject *py_retval;

    self->obj->addColumn();
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_deleteRow(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    unsigned PY_LONG_LONG idx;
    const char *keywords[] = {"idx", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "K", (char **) keywords, &idx)) {
        return NULL;
    }
    self->obj->deleteRow(idx);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_deleteColumn(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    unsigned PY_LONG_LONG idx;
    const char *keywords[] = {"idx", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "K", (char **) keywords, &idx)) {
        return NULL;
    }
    self->obj->deleteColumn(idx);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_matrixDataSize(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    uint32_t retval;

    retval = self->obj->matrixDataSize();
    py_retval = Py_BuildValue((char *) "N", PyLong_FromUnsignedLong(retval));
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_paddingSize(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    int retval;

    retval = self->obj->paddingSize();
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}



PyObject *
_wrap_PyMSDIFMatrix_signature__0(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    PyObject *py_retval;
    char *retval;
    const char *keywords[] = {NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "", (char **) keywords)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return NULL;
    }
    retval = self->obj->signature();
    py_retval = Py_BuildValue((char *) "s", retval);
    return py_retval;
}

PyObject *
_wrap_PyMSDIFMatrix_signature__1(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    PyObject *py_retval;
    char retval;
    const char *keywords[] = {NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "", (char **) keywords)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return NULL;
    }
    retval = self->obj->signature();
    py_retval = Py_BuildValue((char *) "c", (int) retval);
    return py_retval;
}

PyObject * _wrap_PyMSDIFMatrix_signature(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject * retval;
    PyObject *error_list;
    PyObject *exceptions[2] = {0,};
    retval = _wrap_PyMSDIFMatrix_signature__0(self, args, kwargs, &exceptions[0]);
    if (!exceptions[0]) {
        return retval;
    }
    retval = _wrap_PyMSDIFMatrix_signature__1(self, args, kwargs, &exceptions[1]);
    if (!exceptions[1]) {
        Py_DECREF(exceptions[0]);
        return retval;
    }
    error_list = PyList_New(2);
    PyList_SET_ITEM(error_list, 0, PyObject_Str(exceptions[0]));
    Py_DECREF(exceptions[0]);
    PyList_SET_ITEM(error_list, 1, PyObject_Str(exceptions[1]));
    Py_DECREF(exceptions[1]);
    PyErr_SetObject(PyExc_TypeError, error_list);
    Py_DECREF(error_list);
    return NULL;
}


PyObject *
_wrap_PyMSDIFMatrix_info(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    std::string retval;

    retval = self->obj->info();
    py_retval = Py_BuildValue((char *) "s#", (retval).c_str(), (retval).size());
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_applyGain(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    float g;
    const char *keywords[] = {"g", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "f", (char **) keywords, &g)) {
        return NULL;
    }
    self->obj->applyGain(g);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_maximumIndexValue(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    size_t retval;

    retval = self->obj->maximumIndexValue();
    py_retval = Py_BuildValue((char *) "K", ((unsigned PY_LONG_LONG) retval));
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_shiftIndices(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    unsigned PY_LONG_LONG idx;
    const char *keywords[] = {"idx", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "K", (char **) keywords, &idx)) {
        return NULL;
    }
    self->obj->shiftIndices(idx);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_frameSize(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    uint32_t retval;

    retval = self->obj->frameSize();
    py_retval = Py_BuildValue((char *) "N", PyLong_FromUnsignedLong(retval));
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_time(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    double retval;

    retval = self->obj->time();
    py_retval = Py_BuildValue((char *) "d", retval);
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_setTime(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    double t;
    const char *keywords[] = {"t", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "d", (char **) keywords, &t)) {
        return NULL;
    }
    self->obj->setTime(t);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_streamID(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    int32_t retval;

    retval = self->obj->streamID();
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_setStreamID(PyMSDIFMatrix *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int32_t s;
    const char *keywords[] = {"s", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "i", (char **) keywords, &s)) {
        return NULL;
    }
    self->obj->setStreamID(s);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyMSDIFMatrix_matrixCount(PyMSDIFMatrix *self)
{
    PyObject *py_retval;
    uint32_t retval;

    retval = self->obj->matrixCount();
    py_retval = Py_BuildValue((char *) "N", PyLong_FromUnsignedLong(retval));
    return py_retval;
}

static PyMethodDef PyMSDIFMatrix_methods[] = {
    {(char *) "rows", (PyCFunction) _wrap_PyMSDIFMatrix_rows, METH_NOARGS, "rows()\n\n" },
    {(char *) "columns", (PyCFunction) _wrap_PyMSDIFMatrix_columns, METH_NOARGS, "columns()\n\n" },
    {(char *) "newSize", (PyCFunction) _wrap_PyMSDIFMatrix_newSize, METH_KEYWORDS|METH_VARARGS, "newSize(rows, columns)\n\ntype: rows: uint32_t\ntype: columns: uint32_t" },
    {(char *) "resize", (PyCFunction) _wrap_PyMSDIFMatrix_resize, METH_KEYWORDS|METH_VARARGS, "resize(rows, columns)\n\ntype: rows: uint32_t\ntype: columns: uint32_t" },
    {(char *) "resizeRows", (PyCFunction) _wrap_PyMSDIFMatrix_resizeRows, METH_KEYWORDS|METH_VARARGS, "resizeRows(rows)\n\ntype: rows: uint32_t" },
    {(char *) "addRow", (PyCFunction) _wrap_PyMSDIFMatrix_addRow, METH_NOARGS, "addRow()\n\n" },
    {(char *) "addColumn", (PyCFunction) _wrap_PyMSDIFMatrix_addColumn, METH_NOARGS, "addColumn()\n\n" },
    {(char *) "deleteRow", (PyCFunction) _wrap_PyMSDIFMatrix_deleteRow, METH_KEYWORDS|METH_VARARGS, "deleteRow(idx)\n\ntype: idx: size_t" },
    {(char *) "deleteColumn", (PyCFunction) _wrap_PyMSDIFMatrix_deleteColumn, METH_KEYWORDS|METH_VARARGS, "deleteColumn(idx)\n\ntype: idx: size_t" },
    {(char *) "matrixDataSize", (PyCFunction) _wrap_PyMSDIFMatrix_matrixDataSize, METH_NOARGS, "matrixDataSize()\n\n" },
    {(char *) "paddingSize", (PyCFunction) _wrap_PyMSDIFMatrix_paddingSize, METH_NOARGS, "paddingSize()\n\n" },
    {(char *) "signature", (PyCFunction) _wrap_PyMSDIFMatrix_signature, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "info", (PyCFunction) _wrap_PyMSDIFMatrix_info, METH_NOARGS, "info()\n\n" },
    {(char *) "applyGain", (PyCFunction) _wrap_PyMSDIFMatrix_applyGain, METH_KEYWORDS|METH_VARARGS, "applyGain(g)\n\ntype: g: float" },
    {(char *) "maximumIndexValue", (PyCFunction) _wrap_PyMSDIFMatrix_maximumIndexValue, METH_NOARGS, "maximumIndexValue()\n\n" },
    {(char *) "shiftIndices", (PyCFunction) _wrap_PyMSDIFMatrix_shiftIndices, METH_KEYWORDS|METH_VARARGS, "shiftIndices(idx)\n\ntype: idx: size_t" },
    {(char *) "frameSize", (PyCFunction) _wrap_PyMSDIFMatrix_frameSize, METH_NOARGS, "frameSize()\n\n" },
    {(char *) "time", (PyCFunction) _wrap_PyMSDIFMatrix_time, METH_NOARGS, "time()\n\n" },
    {(char *) "setTime", (PyCFunction) _wrap_PyMSDIFMatrix_setTime, METH_KEYWORDS|METH_VARARGS, "setTime(t)\n\ntype: t: double" },
    {(char *) "streamID", (PyCFunction) _wrap_PyMSDIFMatrix_streamID, METH_NOARGS, "streamID()\n\n" },
    {(char *) "setStreamID", (PyCFunction) _wrap_PyMSDIFMatrix_setStreamID, METH_KEYWORDS|METH_VARARGS, "setStreamID(s)\n\ntype: s: int32_t" },
    {(char *) "matrixCount", (PyCFunction) _wrap_PyMSDIFMatrix_matrixCount, METH_NOARGS, "matrixCount()\n\n" },
    {NULL, NULL, 0, NULL}
};

static void
_wrap_PyMSDIFMatrix__tp_dealloc(PyMSDIFMatrix *self)
{
        MSDIFMatrix *tmp = self->obj;
        self->obj = NULL;
        if (!(self->flags&PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED)) {
            delete tmp;
        }
    Py_TYPE(self)->tp_free((PyObject*)self);
}

static PyObject*
_wrap_PyMSDIFMatrix__tp_richcompare (PyMSDIFMatrix *PYBINDGEN_UNUSED(self), PyMSDIFMatrix *other, int opid)
{

    if (!PyObject_IsInstance((PyObject*) other, (PyObject*) &PyMSDIFMatrix_Type)) {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }
    switch (opid)
    {
    case Py_LT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_LE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_EQ:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_NE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    } /* closes switch (opid) */
    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}

PyTypeObject PyMSDIFMatrix_Type = {
    PyVarObject_HEAD_INIT(NULL, 0)
    (char *) "minisdifpy.MSDIFMatrix",            /* tp_name */
    sizeof(PyMSDIFMatrix),                  /* tp_basicsize */
    0,                                 /* tp_itemsize */
    /* methods */
    (destructor)_wrap_PyMSDIFMatrix__tp_dealloc,        /* tp_dealloc */
    (printfunc)0,                      /* tp_print */
    (getattrfunc)NULL,       /* tp_getattr */
    (setattrfunc)NULL,       /* tp_setattr */
#if PY_MAJOR_VERSION >= 3
    NULL,
#else
    (cmpfunc)NULL,           /* tp_compare */
#endif
    (reprfunc)NULL,             /* tp_repr */
    (PyNumberMethods*)NULL,     /* tp_as_number */
    (PySequenceMethods*)NULL, /* tp_as_sequence */
    (PyMappingMethods*)NULL,   /* tp_as_mapping */
    (hashfunc)NULL,             /* tp_hash */
    (ternaryfunc)NULL,          /* tp_call */
    (reprfunc)NULL,              /* tp_str */
    (getattrofunc)NULL,     /* tp_getattro */
    (setattrofunc)NULL,     /* tp_setattro */
    (PyBufferProcs*)NULL,  /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT,                      /* tp_flags */
    "MSDIFMatrix(signature, rows, columns, type)",                        /* Documentation string */
    (traverseproc)NULL,     /* tp_traverse */
    (inquiry)NULL,             /* tp_clear */
    (richcmpfunc)_wrap_PyMSDIFMatrix__tp_richcompare,   /* tp_richcompare */
    0,             /* tp_weaklistoffset */
    (getiterfunc)NULL,          /* tp_iter */
    (iternextfunc)NULL,     /* tp_iternext */
    (struct PyMethodDef*)PyMSDIFMatrix_methods, /* tp_methods */
    (struct PyMemberDef*)0,              /* tp_members */
    0,                     /* tp_getset */
    NULL,                              /* tp_base */
    NULL,                              /* tp_dict */
    (descrgetfunc)NULL,    /* tp_descr_get */
    (descrsetfunc)NULL,    /* tp_descr_set */
    0,                 /* tp_dictoffset */
    (initproc)_wrap_PyMSDIFMatrix__tp_init,             /* tp_init */
    (allocfunc)PyType_GenericAlloc,           /* tp_alloc */
    (newfunc)PyType_GenericNew,               /* tp_new */
    (freefunc)0,             /* tp_free */
    (inquiry)NULL,             /* tp_is_gc */
    NULL,                              /* tp_bases */
    NULL,                              /* tp_mro */
    NULL,                              /* tp_cache */
    NULL,                              /* tp_subclasses */
    NULL,                              /* tp_weaklist */
    (destructor) NULL                  /* tp_del */
};




static int
_wrap_PyMSDIFFrame__tp_init(PyMSDIFFrame *self, PyObject *args, PyObject *kwargs)
{
    const char *signature;
    Py_ssize_t signature_len;
    int32_t streamID;
    const char *keywords[] = {"signature", "streamID", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "s#i", (char **) keywords, &signature, &signature_len, &streamID)) {
        return -1;
    }
    self->obj = new MSDIFFrame(std::string(signature, signature_len), streamID);
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

static PyMethodDef PyMSDIFFrame_methods[] = {
    {NULL, NULL, 0, NULL}
};

static void
_wrap_PyMSDIFFrame__tp_dealloc(PyMSDIFFrame *self)
{
        MSDIFFrame *tmp = self->obj;
        self->obj = NULL;
        if (!(self->flags&PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED)) {
            delete tmp;
        }
    Py_TYPE(self)->tp_free((PyObject*)self);
}

static PyObject*
_wrap_PyMSDIFFrame__tp_richcompare (PyMSDIFFrame *PYBINDGEN_UNUSED(self), PyMSDIFFrame *other, int opid)
{

    if (!PyObject_IsInstance((PyObject*) other, (PyObject*) &PyMSDIFFrame_Type)) {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }
    switch (opid)
    {
    case Py_LT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_LE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_EQ:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_NE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    } /* closes switch (opid) */
    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}

PyTypeObject PyMSDIFFrame_Type = {
    PyVarObject_HEAD_INIT(NULL, 0)
    (char *) "minisdifpy.MSDIFFrame",            /* tp_name */
    sizeof(PyMSDIFFrame),                  /* tp_basicsize */
    0,                                 /* tp_itemsize */
    /* methods */
    (destructor)_wrap_PyMSDIFFrame__tp_dealloc,        /* tp_dealloc */
    (printfunc)0,                      /* tp_print */
    (getattrfunc)NULL,       /* tp_getattr */
    (setattrfunc)NULL,       /* tp_setattr */
#if PY_MAJOR_VERSION >= 3
    NULL,
#else
    (cmpfunc)NULL,           /* tp_compare */
#endif
    (reprfunc)NULL,             /* tp_repr */
    (PyNumberMethods*)NULL,     /* tp_as_number */
    (PySequenceMethods*)NULL, /* tp_as_sequence */
    (PyMappingMethods*)NULL,   /* tp_as_mapping */
    (hashfunc)NULL,             /* tp_hash */
    (ternaryfunc)NULL,          /* tp_call */
    (reprfunc)NULL,              /* tp_str */
    (getattrofunc)NULL,     /* tp_getattro */
    (setattrofunc)NULL,     /* tp_setattro */
    (PyBufferProcs*)NULL,  /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT,                      /* tp_flags */
    "MSDIFFrame(signature, streamID)",                        /* Documentation string */
    (traverseproc)NULL,     /* tp_traverse */
    (inquiry)NULL,             /* tp_clear */
    (richcmpfunc)_wrap_PyMSDIFFrame__tp_richcompare,   /* tp_richcompare */
    0,             /* tp_weaklistoffset */
    (getiterfunc)NULL,          /* tp_iter */
    (iternextfunc)NULL,     /* tp_iternext */
    (struct PyMethodDef*)PyMSDIFFrame_methods, /* tp_methods */
    (struct PyMemberDef*)0,              /* tp_members */
    0,                     /* tp_getset */
    NULL,                              /* tp_base */
    NULL,                              /* tp_dict */
    (descrgetfunc)NULL,    /* tp_descr_get */
    (descrsetfunc)NULL,    /* tp_descr_set */
    0,                 /* tp_dictoffset */
    (initproc)_wrap_PyMSDIFFrame__tp_init,             /* tp_init */
    (allocfunc)PyType_GenericAlloc,           /* tp_alloc */
    (newfunc)PyType_GenericNew,               /* tp_new */
    (freefunc)0,             /* tp_free */
    (inquiry)NULL,             /* tp_is_gc */
    NULL,                              /* tp_bases */
    NULL,                              /* tp_mro */
    NULL,                              /* tp_cache */
    NULL,                              /* tp_subclasses */
    NULL,                              /* tp_weaklist */
    (destructor) NULL                  /* tp_del */
};


#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef minisdifpy_moduledef = {
    PyModuleDef_HEAD_INIT,
    "minisdifpy",
    NULL,
    -1,
    minisdifpy_functions,
};
#endif


#if PY_VERSION_HEX >= 0x03000000
    #define MOD_ERROR NULL
    #define MOD_INIT(name) PyObject* PyInit_##name(void)
    #define MOD_RETURN(val) val
#else
    #define MOD_ERROR
    #define MOD_INIT(name) void init##name(void)
    #define MOD_RETURN(val)
#endif
#if defined(__cplusplus)
extern "C"
#endif
#if defined(__GNUC__) && __GNUC__ >= 4
__attribute__ ((visibility("default")))
#endif


MOD_INIT(minisdifpy)
{
    PyObject *m;
    #if PY_VERSION_HEX >= 0x03000000
    m = PyModule_Create(&minisdifpy_moduledef);
    #else
    m = Py_InitModule3((char *) "minisdifpy", minisdifpy_functions, NULL);
    #endif
    if (m == NULL) {
        return MOD_ERROR;
    }
    /* Register the 'MSDIFMatrix' class */
    if (PyType_Ready(&PyMSDIFMatrix_Type)) {
        return MOD_ERROR;
    }
    PyModule_AddObject(m, (char *) "MSDIFMatrix", (PyObject *) &PyMSDIFMatrix_Type);
    /* Register the 'MSDIFFrame' class */
    if (PyType_Ready(&PyMSDIFFrame_Type)) {
        return MOD_ERROR;
    }
    PyModule_AddObject(m, (char *) "MSDIFFrame", (PyObject *) &PyMSDIFFrame_Type);
    return MOD_RETURN(m);
}
